-- 第五步：创建用户状态表
CREATE TABLE IF NOT EXISTS user_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) DEFAULT 'OFFLINE',
    call_price DECIMAL(10,2) DEFAULT 0.00,
    message_price DECIMAL(10,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 插入用户状态数据
INSERT INTO user_status (user_id, status, call_price, message_price, created_at, updated_at) VALUES
(1001, 'FREE', 300.00, 10.00, NOW(), NOW()),
(1002, 'BUSY', 200.00, 8.00, NOW(), NOW()),
(1003, 'ONLINE', 350.00, 12.00, NOW(), NOW()),
(1004, 'OFFLINE', 500.00, 15.00, NOW(), NOW()),
(1005, 'ONLINE', 250.00, 9.00, NOW(), NOW()),
(1006, 'OFFLINE', 180.00, 6.00, NOW(), NOW()),
(1007, 'ONLINE', 320.00, 11.00, NOW(), NOW()),
(1008, 'OFFLINE', 280.00, 10.00, NOW(), NOW()),
(1009, 'ONLINE', 400.00, 14.00, NOW(), NOW()),
(1010, 'OFFLINE', 150.00, 5.00, NOW(), NOW());
