-- 生成真实用户数据脚本
-- 用于首页用户卡片显示

-- 清空现有用户数据（保留测试用户）
DELETE FROM wallets WHERE user_id NOT IN (86945008);
DELETE FROM transactions WHERE user_id NOT IN (86945008);
DELETE FROM users WHERE id NOT IN (86945008);

-- 插入真实用户数据
INSERT INTO users (id, username, password, phone, email, nickname, avatar_url, gender, birthday, location, bio, is_active, is_online, created_at, updated_at) VALUES
-- 用户1 - 不吃香菜
(1001, 'user_1001', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', '13800138001', 'user1001@example.com', '不吃香菜', 'https://picsum.photos/200/200?random=1', 'FEMALE', '1999-05-15', '北京', '我是一个活泼开朗的女孩，喜欢聊天和交朋友。希望能遇到有趣的人一起分享生活的美好。', true, true, NOW(), NOW()),

-- 用户2 - 你的菜
(1002, 'user_1002', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', '13800138002', 'user1002@example.com', '你的菜', 'https://picsum.photos/200/200?random=2', 'FEMALE', '2001-03-22', '广州', '温柔可爱的女孩，喜欢听音乐和看电影。希望能找到志同道合的朋友。', true, false, NOW(), NOW()),

-- 用户3 - 小仙女
(1003, 'user_1003', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', '13800138003', 'user1003@example.com', '小仙女', 'https://picsum.photos/200/200?random=3', 'FEMALE', '1998-08-10', '上海', '充满正能量的女孩，喜欢运动和旅行。希望能遇到有趣的人一起分享快乐。', true, true, NOW(), NOW()),

-- 用户4 - 甜心宝贝
(1004, 'user_1004', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', '13800138004', 'user1004@example.com', '甜心宝贝', 'https://picsum.photos/200/200?random=4', 'FEMALE', '1996-12-05', '深圳', '成熟稳重的姐姐，善解人意，喜欢读书和品茶。希望能找到真诚的朋友。', true, false, NOW(), NOW()),

-- 用户5 - 阳光女孩
(1005, 'user_1005', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', '13800138005', 'user1005@example.com', '阳光女孩', 'https://picsum.photos/200/200?random=5', 'FEMALE', '2000-07-18', '杭州', '热爱生活的阳光女孩，喜欢摄影和美食。希望能记录下每一个美好瞬间。', true, true, NOW(), NOW()),

-- 用户6 - 文艺青年
(1006, 'user_1006', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', '13800138006', 'user1006@example.com', '文艺青年', 'https://picsum.photos/200/200?random=6', 'FEMALE', '1997-11-30', '成都', '文艺范十足的女孩，喜欢诗歌和艺术。希望能找到懂我的人。', true, false, NOW(), NOW()),

-- 用户7 - 运动达人
(1007, 'user_1007', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', '13800138007', 'user1007@example.com', '运动达人', 'https://picsum.photos/200/200?random=7', 'FEMALE', '1999-04-12', '武汉', '热爱运动的健康女孩，喜欢跑步和瑜伽。希望能找到一起运动的伙伴。', true, true, NOW(), NOW()),

-- 用户8 - 音乐爱好者
(1008, 'user_1008', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', '13800138008', 'user1008@example.com', '音乐爱好者', 'https://picsum.photos/200/200?random=8', 'FEMALE', '2002-01-25', '西安', '音乐是我的生命，喜欢各种类型的音乐。希望能找到音乐上的知音。', true, false, NOW(), NOW()),

-- 用户9 - 旅行者
(1009, 'user_1009', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', '13800138009', 'user1009@example.com', '旅行者', 'https://picsum.photos/200/200?random=9', 'FEMALE', '1995-09-08', '重庆', '世界那么大，我想去看看。喜欢探索未知的地方，希望能找到旅行的伙伴。', true, true, NOW(), NOW()),

-- 用户10 - 美食家
(1010, 'user_1010', '$2a$10$N.zmdr9k7uOCQb376NoUnuTJ8iAt6Z5EHsM8lE9lBOsl7iKTVEFDi', '13800138010', 'user1010@example.com', '美食家', 'https://picsum.photos/200/200?random=10', 'FEMALE', '1998-06-14', '南京', '美食是我的最爱，喜欢尝试各种美味。希望能找到一起品尝美食的朋友。', true, false, NOW(), NOW());

-- 为每个用户创建钱包
INSERT INTO wallets (user_id, balance, frozen_amount, currency, created_at, updated_at) VALUES
(1001, 300.00, 0.00, 'CNY', NOW(), NOW()),
(1002, 200.00, 0.00, 'CNY', NOW(), NOW()),
(1003, 350.00, 0.00, 'CNY', NOW(), NOW()),
(1004, 500.00, 0.00, 'CNY', NOW(), NOW()),
(1005, 250.00, 0.00, 'CNY', NOW(), NOW()),
(1006, 180.00, 0.00, 'CNY', NOW(), NOW()),
(1007, 320.00, 0.00, 'CNY', NOW(), NOW()),
(1008, 280.00, 0.00, 'CNY', NOW(), NOW()),
(1009, 400.00, 0.00, 'CNY', NOW(), NOW()),
(1010, 150.00, 0.00, 'CNY', NOW(), NOW());

-- 为每个用户创建初始交易记录
INSERT INTO transactions (user_id, type, amount, balance_after, description, status, created_at) VALUES
(1001, 'RECHARGE', 300.00, 300.00, '初始充值', 'SUCCESS', NOW()),
(1002, 'RECHARGE', 200.00, 200.00, '初始充值', 'SUCCESS', NOW()),
(1003, 'RECHARGE', 350.00, 350.00, '初始充值', 'SUCCESS', NOW()),
(1004, 'RECHARGE', 500.00, 500.00, '初始充值', 'SUCCESS', NOW()),
(1005, 'RECHARGE', 250.00, 250.00, '初始充值', 'SUCCESS', NOW()),
(1006, 'RECHARGE', 180.00, 180.00, '初始充值', 'SUCCESS', NOW()),
(1007, 'RECHARGE', 320.00, 320.00, '初始充值', 'SUCCESS', NOW()),
(1008, 'RECHARGE', 280.00, 280.00, '初始充值', 'SUCCESS', NOW()),
(1009, 'RECHARGE', 400.00, 400.00, '初始充值', 'SUCCESS', NOW()),
(1010, 'RECHARGE', 150.00, 150.00, '初始充值', 'SUCCESS', NOW());

-- 创建用户状态表（用于存储在线状态和价格信息）
CREATE TABLE IF NOT EXISTS user_status (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    status VARCHAR(20) DEFAULT 'OFFLINE', -- ONLINE, OFFLINE, BUSY, FREE
    call_price DECIMAL(10,2) DEFAULT 0.00,
    message_price DECIMAL(10,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id)
);

-- 插入用户状态数据
INSERT INTO user_status (user_id, status, call_price, message_price, created_at, updated_at) VALUES
(1001, 'FREE', 300.00, 10.00, NOW(), NOW()),
(1002, 'BUSY', 200.00, 8.00, NOW(), NOW()),
(1003, 'ONLINE', 350.00, 12.00, NOW(), NOW()),
(1004, 'OFFLINE', 500.00, 15.00, NOW(), NOW()),
(1005, 'ONLINE', 250.00, 9.00, NOW(), NOW()),
(1006, 'OFFLINE', 180.00, 6.00, NOW(), NOW()),
(1007, 'ONLINE', 320.00, 11.00, NOW(), NOW()),
(1008, 'OFFLINE', 280.00, 10.00, NOW(), NOW()),
(1009, 'ONLINE', 400.00, 14.00, NOW(), NOW()),
(1010, 'OFFLINE', 150.00, 5.00, NOW(), NOW());
