# 第三方认证配置
app:
  alipay:
    app-id: ${ALIPAY_APP_ID:}
    private-key: ${ALIPAY_PRIVATE_KEY:}
    public-key: ${ALIPAY_PUBLIC_KEY:}
    gateway-url: https://openapi.alipay.com/gateway.do
    notify-url: ${APP_BASE_URL:http://localhost:8080}/api/auth/third-party/alipay/callback
    
  wechat:
    app-id: ${WECHAT_APP_ID:}
    app-secret: ${WECHAT_APP_SECRET:}
    mch-id: ${WECHAT_MCH_ID:}
    api-url: https://api.weixin.qq.com
    notify-url: ${APP_BASE_URL:http://localhost:8080}/api/auth/third-party/wechat/callback

# 认证配置
auth:
  third-party:
    timeout-minutes: 30  # 认证超时时间（分钟）
    max-attempts: 3      # 最大尝试次数
    retry-interval: 300  # 重试间隔（秒）
