# 主配置文件
spring:
  profiles:
    active: default  # 默认使用default配置
    # include: payment  # 暂时禁用支付配置
  
  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/socialmeet?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          time_zone: Asia/Shanghai
        connection:
          zeroDateTimeBehavior: convertToNull
    open-in-view: false

# 服务器配置
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# 极光推送配置
jpush:
  app:
    key: ff90a2867fcf541a3f3e8ed4
  master:
    secret: 112ee5a04324ae703d2d6b3d
  apns:
    production: false
  time:
    to:
      live: 60
  statistics:
    enabled: true
  retry:
    times: 3
    interval: 1000

# Swagger/OpenAPI 配置
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true

# Redis配置 - 禁用Redis自动配置以避免JPA Repository冲突
# spring.data.redis.host=localhost
# spring.data.redis.port=6379
# spring.data.redis.password=
# spring.data.redis.database=0
# spring.data.redis.timeout=2000ms
# spring.data.redis.lettuce.pool.max-active=8
# spring.data.redis.lettuce.pool.max-wait=-1ms
# spring.data.redis.lettuce.pool.max-idle=8
# spring.data.redis.lettuce.pool.min-idle=0

# 阿里云配置
aliyun:
  # 号码认证配置 (支持三大运营商)
  phone-auth:
    access-key-id: "LTAI5tJFtviyom7ULbvYrPqX"
    access-key-secret: "c5sa292YiWe21jIbdwQibg4iT1YZRv"
    region-id: "cn-hangzhou"
    app-key: "FA000000008490514065"
    app-secret: "请从融合认证方案详情中获取AppSecret"
    # 号码认证服务配置
    service-name: "Dypnsapi"
    # 支持功能: 一键登录、号码校验、本机号码校验
    supported-features: ["ONE_CLICK_LOGIN", "PHONE_VERIFY", "SELF_PHONE_VERIFY"]
  
  # SMS配置
  sms:
    access-key-id: your_access_key_id
    access-key-secret: your_access_key_secret
    sign-name: 您的签名
    template-code: SMS_123456789
    endpoint: dysmsapi.aliyuncs.com