# 支付配置文件
payment:
  # 支付宝配置
  alipay:
    app-id: ${ALIPAY_APP_ID:2021005195696348}
    private-key: |
      -----BEGIN PRIVATE KEY-----
      MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDqB+lFYhZb4HYq
      ZbFuJnssWHtIWpq7eiMHtgEjMfUx7GsCVjewS+ERFvZArsBIapBS3xld5YyHgGB6
      hpNGyOHYHypDL5Eco+hpa6GgkX6HX3QwHj30sVjljNQ956BzuwfWbVxQe7kgDXwe
      dvVRM7eA3o7yiEtYqXWZiPyAQgAdwBHvus/ff1+E/LnSDgfUKm0186WxvNdTZxzb
      tXyerMXSQ85bPc7G6ECldqWwa6d24g+Ao+wRwi0oSTcti4X8xjWAbkcq9UW/HAJC
      RDYQZlFLQcjOStyqMQ/qSOtu+ZIUHA1trVi1l9ujHA2Hl0zl99yjG2WDru0k2MVB
      vkD7ekC9AgMBAAECggEABYflVUHxrv8u27v72v4RfXqj2JG87r7+spvJtW1kqDw4
      SohYwukFgH657Xe+d0JUIdlAQ2NS6brjd3x/C4u2Jqzp4JzwVtca0tmmgAx1izkl
      c6OrVCvteBNWysBoHtll4IVEyr7PIQ5LMiRz52o2T9cyqqcE8itNv7ComFa2+Pz5
      qCm2PKFvT6t7YAuW1OkgJE5eu5Px6ziWa+JKhgCxKACEPMujEgqrfA7BnaxP1TkD
      s3f5+6cEn2nzQO0NjEQifR2n5Vu6/Pk6PjcQn6hSL1VQGksK0l7Z//K5hhqJ33RF
      UpRYBcOlv6oFDbtj6lVyBF93HZn1bbqYqoNbO412MQKBgQDxcn5KoZGZoU6mfHd7
      itADRyyCVean1amPMRe7wGvswOyapSTnmeL8mNu2tzN69nBmvf2kDmBhBp2dXFqo
      TaX0hNPNow7/A5XXORebTLD/ZHUopODWEg/fWRRXAZFA909YwE0rJVNY1JbnHdFE
      B2wRjsUz14ZjTiBU5lhCFKNMVQKBgQD4IvwMTm3S7f1Lhud5xknnc3H7ZU+ryT9V
      joKURm4qPvxrqf9ANTCmIuEDc/vJ2RcDOsFeXE44fNA2JI3tFedMX6j2fAh8/sJ9
      OEjsL58WZpfT0tXpKQdtNH+Dka1o/1rjbDnCfuJwdq52iP6JukLmPm6vjdf79w6n
      GoUjlSgKyQKBgQDwv0wEGHQ4rqngwazVp8Tf7+EGmKaj5Rzr5XSXxjcW3AtP66kP
      sdauLbCu0J9pVT8ggwLcyWT6egFA/ex7cukuFh+nJJZ4WtfWwVuzg1XdYgqcG0MA
      0QO4nXb1hl+SWsZoZV7Mzav8oAVTr9yQq6HrI+OoXJfofucoIIISacel/QKBgQCS
      FU6cFCRV9OSVbXOjXpit2Wp2XZu8//r4bLD1iE1dM725yNhMPcRJWulr9gF7QQJq
      VVH4MpGeceTGq1ifBrEoZnz7t+PrarSnsdZErniTYIzsGQj0fsIviaO0mrQjx4oD
      r/iFR9wZ59UoVdi8ztqJ4KGbWv+YCEgpGtTdMPfk+QKBgEtBsLIn6nB9Z3kxszEp
      dNOUCBZVduIrSrprpwxv8KZeScZGj7YK6hBNVQ4WqGfsQu/LDzmxdNmJmLzikIjc
      5e8qbKbPro22s7/rVudTqcuIhzZimElea+jxuIgIpFmT4k1KwL7JxvEtcNG/cfvJ
      pR0dSZbITFu4rfL6Id5BpFy5
      -----END PRIVATE KEY-----
    public-key: |
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA...
    alipay-public-key: |
      MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAgxU8Ld4qgs08Uvqn/EpO6KQ4n1TwRnxDjpEjBjuwp3RmJxvytX0tkaE+/B7Wt2m5tzlNJjEfxKLAvFrsIX8IC8/gTVW7c0vMCHlUW0YEAPlhnuMMXVQIDKKJqUQ/wUAeWy4Isss2gSJGMgsqKz+Mi8ITK2d803ReKESN0pDnJCWS0m7dl2oOi3yNQNW+5Km5la8wv7v0qWvbMChgtj5Y2PcGYQC9x9XBzrTm6eKIJP667MzxbDc7dtxBV+NXcDY8e+xSdNdc9z7i4WCoet00N9zbn7E8cfU4Qb0joHh8kXIMmUnBWQ2oyxc/Wzcr/WOMTs9mzBOn93HLLAilC3KxyQIDAQAB
    server-url: https://openapi.alipay.com/gateway.do
    format: json
    charset: UTF-8
    sign-type: RSA2
    notify-url: ${SERVER_BASE_URL:http://localhost:8080}/api/recharge/callback/alipay
    return-url: ${SERVER_BASE_URL:http://localhost:8080}/api/recharge/return/alipay
  
  # 微信支付配置
  wechat:
    app-id: ${WECHAT_APP_ID:your_wechat_app_id}
    mch-id: ${WECHAT_MCH_ID:your_wechat_mch_id}
    api-v3-key: ${WECHAT_API_V3_KEY:your_wechat_api_v3_key}
    private-key-path: ${WECHAT_PRIVATE_KEY_PATH:classpath:wechat_private_key.pem}
    certificate-serial-number: ${WECHAT_CERTIFICATE_SERIAL_NUMBER:your_certificate_serial_number}
    server-url: https://api.mch.weixin.qq.com
    notify-url: ${SERVER_BASE_URL:http://localhost:8080}/api/recharge/callback/wechat
    return-url: ${SERVER_BASE_URL:http://localhost:8080}/api/recharge/return/wechat

---
# 开发环境配置
spring:
  config:
    activate:
      on-profile: dev
      
payment:
  alipay:
    server-url: https://openapi.alipaydev.com/gateway.do  # 沙箱环境
    notify-url: http://localhost:8080/api/recharge/callback/alipay
    return-url: http://localhost:8080/api/recharge/return/alipay
  wechat:
    notify-url: http://localhost:8080/api/recharge/callback/wechat
    return-url: http://localhost:8080/api/recharge/return/wechat

---
# 生产环境配置
spring:
  config:
    activate:
      on-profile: prod
      
payment:
  alipay:
    server-url: https://openapi.alipay.com/gateway.do  # 正式环境
  wechat:
    server-url: https://api.mch.weixin.qq.com  # 正式环境
